loginauth/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views
from .views import home, disconnect
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name = 'home'),
    path('login/', views.LoginView.as_view(), name = 'login'),
    path('logout/', views.LogoutView.as_view(), name = 'logout'),
    path('auth/', include('social_django.urls',namespace='social')),
    path('disconnect/', disconnect, name = 'disconnect')
]

loginauth/views.py
from django.shortcuts import render


def home(request):
	return render(request, 'home.html')

def disconnect(request):
	return render(request, 'disconnect.html')

loginauth/templates/disconnect.html
{% extends "layout.html" %}


{% block content %}

<!-- <form id="myform" method="post" action="{% url 'social:disconnect' 'google-oauth2' %}5/?next={{request.path }}">
    {% csrf_token %}
    <input type="hidden" name="name" value="value" /> 
    <a onclick="document.getElementById('myform').submit();">discon</a>
</form> -->

<a href="{% url 'home' %}" onclick="signOut();">Sign out</a>
<script>
  function signOut() {
    var auth2 = gapi.auth2.getAuthInstance();
    auth2.signOut().then(function () {
      console.log('User signed out.');
    });
  }
</script>

{% endblock %}

loginauth/templates/home.html
{% extends "layout.html" %}

{% block content %}
	{% if user.is_authenticated %}
            <p class="display-4">Hello, {{ user.username }}</p>
            <br>
            <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
	{% else %}
    <a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a><br>
	{% endif %}
{% endblock content %}

loginauth/templates/layout.html
<!DOCTYPE html>
<html>
<head>
	<title>Sprint</title>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
</head>
<body>
	<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
		<div class="container">
				<a class="navbar-brand" href="/">Sprint Dashboard</a>
		</div>  
	</nav>
    <div class="container">
	    {% block content %}	
	    {% endblock content %}
    </div>
</body>
</html>